### ISSUE TITLE
MBAC in Noesis

### ISSUE THREAD

**Issue by Durik256** [j2me-preservation/MascotCapsule#11]
Hi) Why not make a Noesis plugin based on your work?

**Comment by minexew** [comment]
You have my full encouragement ;)

**Comment by Durik256** [comment]
yesterday looked at what you answered)) thought you would do it since I don't know python ... xD
But I created a thread on the forum and no one answered there. I tried it myself and it worked, only models with triangular faces are loaded ... (oh yes, my code is terrible) In general, I need your help))
link:
https://drive.google.com/file/d/1oux6T2vTb3asflGppbIJzbMV5nC1lrks/view?usp=sharing

**Comment by Durik256** [comment]
he is ready for a long time
problem with uvs
